export const Users = [
  {
    id: 1,
    profilePicture: "assests/person/1.jpg",
    username: "reza",
  },
  {
    id: 2,
    profilePicture: "assests/person/2.jpg",
    username: "tiara",
  },
  {
    id: 3,
    profilePicture: "assests/person/3.jpg",
    username: "dianutami",
  },
  {
    id: 4,
    profilePicture: "assests/person/4.jpg",
    username: "sherlyn",
  },
  {
    id: 5,
    profilePicture: "assests/person/5.jpg",
    username: "vikry",
  },
  {
    id: 6,
    profilePicture: "assests/person/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: "assests/person/6.jpg",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "assests/person/7.jpeg",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "assests/person/8.jpeg",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "assests/person/seni.png",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "painting is art.",
    photo: "assests/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assests/post/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assests/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assests/post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assests/post/5.png",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assests/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assests/post/7.png",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assests/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assests/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assests/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
